package com.example.demo.Entites;



import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "threat_alerts")
public class ThreatAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Alert Basic Info
    @Column(nullable = false)
    private String alertType;  
    // Could be: EMAIL_THREAT, LOG_ANOMALY, NETWORK_INTRUSION, CORRELATED_ATTACK

    @Column(columnDefinition = "TEXT")
    private String description;  // Summary of the detected issue

    @Column(columnDefinition = "TEXT")
    private String llmAnalysis;  // Full explanation from LLM

    @Column
    private double riskScore;  // 0–100 risk level (generated by LLM/correlation system)

    @Column(nullable = false)
    private LocalDateTime timestamp = LocalDateTime.now();

    @Column
    private boolean isResolved = false;

    @ManyToOne
    @JoinColumn(name = "employee_id")
    @JsonBackReference("employee-threats")
    private Employee employee;

    @ManyToOne
    @JoinColumn(name = "analyst_id")
    @JsonBackReference("analyst-threats")
    private SecurityAnalyst analyst;



    // Optional fields: reference to email or log
    @Column
    private Long attackEmailId; // Null if not related to email threat

    @Column
    private Long logId; // Null if not related to log anomaly

    @Column
    private Long ipScanId; // Placeholder for Network/IP events

    // Constructors
    public ThreatAlert() {}

    public ThreatAlert(String alertType, String description, Employee employee) {
        this.alertType = alertType;
        this.description = description;
        this.employee = employee;
    }

    // Getters & Setters

    public Long getId() {
        return id;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLlmAnalysis() {
        return llmAnalysis;
    }

    public void setLlmAnalysis(String llmAnalysis) {
        this.llmAnalysis = llmAnalysis;
    }

    public double getRiskScore() {
        return riskScore;
    }

    public void setRiskScore(double riskScore) {
        this.riskScore = riskScore;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isResolved() {
        return isResolved;
    }

    public void setResolved(boolean resolved) {
        isResolved = resolved;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public SecurityAnalyst getAnalyst() {
        return analyst;
    }

    public void setAnalyst(SecurityAnalyst analyst) {
        this.analyst = analyst;
    }

    public Long getAttackEmailId() {
        return attackEmailId;
    }

    public void setAttackEmailId(Long attackEmailId) {
        this.attackEmailId = attackEmailId;
    }

    public Long getLogId() {
        return logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    public Long getIpScanId() {
        return ipScanId;
    }

    public void setIpScanId(Long ipScanId) {
        this.ipScanId = ipScanId;
    }
}

